from flask import Flask, render_template, request ,redirect, url_for
from datetime import date


app = Flask(__name__)

# 👇 Add this line to fix the error
letters = list("ABCDEFGHIJKLMNOPQRS")
start_date = date(2025, 8, 1)

# Messages from A to S (1st to 20th Aug)
messages = [
    {"date": "August 1", "letter": "A", "text": "HEY Shuppandii!!😜You Surprised???👻 HEHEHHEEEEEEE ,I am evil😈,if you are surprised sent me a selfie 🙂‍↕️ I know you are surprised did you expected this..😁Soooo today is August 1 ,your birth month and from today to the day you born ,every day you will have a message from me so DON'T FORGET TO CHECK🤗.THE LETTER A stands for AMAZING ,Yes you are such an amazing guy for me🤗,My super hero is YOU as you have such an amazing personality,loyality,your dumbass behaviour,your dedication ,Hardwork everything amaze me,what I want to say is that I LOVE YOU SOOO MUCH Kunjuppaaaa🫶🏽there is a biggg smile on your face, right??? undekkilu vekkam a chiri ene koodi kanichu thaaa pic ayachollu ,ente kunju pine VIP aya kondu vdo call onum cheyiila ariyam athu kondu choikkunilla... very busy person alle (upcoming pm) even if I can't seee that konthrapallu vechittulla smile 😂 I know...I am happy and soo much grateful to have you in my life,yeah we fight sometimes i feel like how can you be this much stupid pinew thallaku sukem illatha kochu ahh vicharichu shemikkunna aaa 😌 nthanekilum entee makri kunju kshemikkanem US,WE are for life time there is noo going back for you njan palathum vannu pareyum athokke sahichonem kettalooo ,E month full happy ayy irikkatte frnds ellarum busy ayy ente kode kore time spend cheyyan pattatew🫣Every thing is just my random thoughts,Anyway you are such an AMAZING guy I am blessed ,Appoo egane happy aleee shundrii ,I hope I made your day🥰,Appo innathekku ithrem ollu ,Nale Pakkalam bye bye👋 I LOVE YOU Kuruneri😘Things are awaiting for you in the coming days,lets seeeee"},
    {"date": "August 2", "letter": "B", "text": "HOLA MR.Shuppuu😁,soo you exited for day 2.message open akki enkil vekm oru heart itte vannu ...arambikkalamaa .....👀Being with you is my favorite part of life 🥰 Enikku bhayakkara ishtta ninte kode time spend cheyyan bhayyakkara bhayyakara ishttaaa ,even if ni enikku patti post tharumekkilum ,oro time ente shudri 5,10,min alla ara hr,one hr 🥵,ithrem post tharumekkilum,enikku dheshyem vanna pranthu pidichalum ichiri nerem kode irikkumbol aggu thanukkum 😫,its soo fun spending time with you🥰you make me laugh ,i make you crazyyy🤪I still remember that beach day nthu resayirunnu,ayoo enikku sangadem varum athu aloikkumbol ,ente kochu a turf poy kalichittu kalilu nerum vechu angu poy aa ktm bike eduthondu vannathu annu enikku kore nerem post thannekilum (ithente karym njan nale pareya.waitt...)enikku beach ishttayakondu enew kondu povan vendi ntte kochu pavem ,enittu pinew helmet edukkan thirichu poyathum ,it was an unforgetable day but still when thinking things that you done that day it still ache my heart,still nammal ethra oke day spend cheythittundekil first date is always special .I was very happy that day nammal ethra nerem avide irunu vellathil ereggi pinew ariyaloo...kutti kuruneri,nammal othiri samasarichu,njan orkkunundu enikku pistha shake umm chilly chicken puffs vaggi thanee😭enitu pona vazhi .... athu njan day 10 pareyam... apoo kunji mani odikkoo bye byee LOVE YOU PAPPUU "},
    {"date": "August 3", "letter": "C", "text": "Wahhh...today is day 3 ,open akki enkilum odi vannu enikku oru present itoo 🙂‍↕️ todays topic is about caring ,charming YOU, ph koodi athra caring alelum nerittu kanumbol you treat me like a princess👸ninakku ariyumo areela njan sherikum iganetha karyggalil oru fairy tale,fantacy ishtapedunna alla e movie oke kanille athinathe pole ok experience cheyyanem ni ene agane treat cheyyanm enoke agrehikkum ,but ni nintethaya wayil very romantic aa but  onnu anime,fight,game, car okke matti vechu ichiri romatic movie okke kandal sooper avumm kore koodii (365 days allatoo 🥱) sometime just sit and think about us ,our relationship ,all the phases just reflect on it and be thoughfull may it will amaze you and you will understand or realize soo many things...just in case just pure thoughts...give it a try... ph koodi ulla karym atto pareyane, because ippo nammal kananillalo appo athu ahnallo important... to keep that freshness of relatonship till end .Njan ippozhum a first phase ill thaneyya I know you moved on from that phase but enikku still aaa excitment um ni eppo vilikum ,mess ayyacho aa oru kathirippu enikku ippozhum undu e kunji kunji karyggal ninnodu share cheyyanem even if its not relevent ,I expect you to do the same ,i dont want to compell but just expressing it.Actully ni pareyule ninte negetive side mathreme njan kanarollu ennu agane onum alla entee kochinte positive side njan sredhikkarundu njan pinew pareyathatha ,njan ni cheyunna oro kunji karym note cheyyarundu athu chellapol ni polum ariyathe cheyunna karym ayirikkum ennalum ,ni njan scooter kerumbol stand ittu tharunnathum,enikku helmet ittu tharunnathum ,athu oori tharunnathum,ennikku tholu venikkumbol bag uri ni pidikkunathum ,enne soap iddan laddu vaggi kondu varunnathu 🥺,kochinte hardwork ,enikku rose vaggi tharunnathu ,kunji kunji surprise tharunnathu ellam enikku ishtta ,njan kandathil vechu you are such a good human being ni igane oke cheyyunathu kondalla ,but above all of that you are such a great person,I am lucky I guess🙂‍↕️.Innathekku ithrem ollu kunju puzhu odikkoo nale kannatoo bye byeeee😁Dont mistake it for the most romantic or cutest thing ,wait for DAY 5 i will tell you something....there is moreee LOVE YOU BUMBUDU "},
    {"date": "August 4", "letter": "D", "text": "Dear love.. ennu parenju thodegana thalparym buttt Daaaaa patttiiii marythekku ente harine enikku thirichu thannooo 😈....ente kochinte dhehathu keri irikkunna aale erekki vitto...request ahnuuuu👀...deyy snehathode pareyuva you are changing and stop that change and goo back to who you are or who you were emotionally or from heart..work oke pressure undavumayirikkum nalla super ayy work oke cheyyaa ,ene edekku orkuvaaa ,othiri stress oke adikathe work cheyyuva ilel mudi oke narechu pokkum ketto mr.what I want to describe about you is that you are very hardworking,dedicated,dreamful,the effort you put in your work everything I am giving you a hatts off to all this continue doing it you reach the best heights eniitu venem enew ponnu pole nokkan (orkkunundo ithoke parenju🥱)marythekku enikku thanna vakkuu palleechonem ilel njan sharky vetti kaleyum orthoo...I love you😫"},
    {"date": "August 5", "letter": "E", "text": "Its just day 5 are you reading this or you busy with work.shuppuu nanny sooper ayy work oke cheythu ellarem njettikkanem i know kochu sooper ayy cheyyumenu....ni sherikkum oro karythil idunna effort🥰 EFFORT the little to big one we both make..even if they are unnoticed sometimes..love is not all about the gifts the flower you gave me or anything ..its the effort to stay even when we are tired of eachother ,its the effort to stay even when the situations and life pulls us away ..this whole countdown its my way of showing effort ,that I  choose you ,I am here for you ..even on hard days when you were busy,when i feel distant ..even if your effort not always match mine but its still come from a place of love thats enough for me njan vekkam varaatttooo aggottu ennoke pareyummm january avmbozhekkum ntte course oke kazhiyum ee 2 month 3 month oke matti vechu kochu pattuvanel ella month varan nokkutto shundrii I know your financial situation but just tryyyy..I love you kunjaaaa🥰"},
    {"date": "August 6", "letter": "F", "text": "Hey shuppandi kundiii eni ethra nall wait cheythala onnu kannan pattaaaa ninaku ene kanenm valla chintha ondoda marappattti ondel innuu vilichituu enikku pavapetta veetile payyan padi thannonem athoke ketittu varsheggal ayy😈 hummmmm......i have soo much faith in you ...you are a person who neverr give up on things thats easily it doest matter how much hard painfull the way is once you have eye on something there is no going back for you until you achieve that aand i find it as a very fine and unique quality of yours and I gave all heart to you I hope that uou protect and keep it safe in your hands and as you never giveup on any i have faith in you that you never give up on me also ....dont you dare..hmm...you are such a strong person ,fearless,fayyyankkaarenn thanneyaaa...LOVE YOU,Be Happy ,Have a nice day nale kanamm work pressure korevu ahnell"},
    {"date": "August 7", "letter": "G", "text": "Hey My love,Hows your days are going...are reading it every day are you keeping up with it????I dont whether I am making you bore...today what i want to tell you is that I am so grateful for you ,grateful for having you in my life and most important i am grateful to have a gentle man,gentle you,You were always gentle towards me ,where can I get a man like this not even in amazon or flipkart ,HeeHeee....you are such a beautiful gentle man that I always wanna keep I Love you "},
    {"date": "August 8", "letter": "H", "text": "hey heyy marapattiii  makkriii actually I feels like you are my Home I feel safe around you I am happy with you ,your smile makes me melt like ice cream ,I love your smile I always want you to keep that smile ...You are my person and I dont wanna share you even with your friends (you GAY bitchh😈)As you will be extremely busy on thses days I dont want to ...so edekkoke break edekkuva ,happy ayy irikkuva LOVE YOU"},
    {"date": "August 9", "letter": "I", "text": "Hey shuppu Welcome to day 9!!! I LOVE YOU,I LOVE YOU TO THE INFINITY AND BEYOND ,I LOVE YOU TO THE MOON AND BACK , I LOVE YOU IN EVERY UNIVERSE ,I LOVE YOU SO MUCH ,I LOVE YOU THE MOST ,I LOVE YOU 3000,I ADORE YOU ,I RESPECT YOU,What I want to tell you today is that I’ll always be here for you,No matter how hard your life is ,how sad you are i will be always there for you ,and you should know that if you are unhappy you can come to me i am also your happy place ,but you rarely do that,i will be always with you in all of your ups and downs,your problem is also my problem ,as i am very obsessed in the story of lord shiva and parvati ,that was such a pure ,blissful ,unconditional love right ,so like that i am not only just your partner i am your other half dear,May universe give you all happiness in life ,less stressful,more happy life and days I am not sugar cotting you Yes baby we fight I am not ignoring the fact ,and all the its me  I am the one who picks fight ,but it has reasons ,may universe give you the brain to understand that HEHHEEE its all part of this relationship ,When you choose ,you didnt just choose me okay ,my craziness,lazziness,my imperfections,everything was there on the package from the begining .I really miss you soo muchh ,do you also miss me??? I always choose you no matter what.You are Irreplaceable for me Ok Bye Bye nale kanatooo I LOVE YOU"},
    {"date": "August 10", "letter": "J", "text": "Broooo Egane povunnu kunje nintte work okkeee ..when I look back into the past our journey was quite happy ,beautiful,clumsy,But I am not the same I changed a lot because of you ...Ni poyalum enikku oru pullum illa enna ithil ninnum ni poya njan chathu kalayana stage ayy 😂...ghorem ghorem self love padikkondirunna njan athokke nthannu vare marennu poyy patttiii ..LOVE YOU ,WORK OKE SUPER AYY CHEYTHU KODUKKUVA ALL THE BEST FOR TODAY"},
    {"date": "August 11", "letter": "K", "text": "Kunjipappuveeeee😘😘Kalla kuruneriii sugem thanne chellakili,kochinu work ullathu kondu thanwe njan content oke kurekkuvatto shuppandiii just keep it in your mind that njan mudi otti pidichirikkuna bubble gum poleya i am never gonna leave you ni vicharikkum mudi vetti kalenja porennu I will kill youu panndii kunddiii...pinew be kind to yourself you are sometimes doing too much work and be kind to me also ..kunndiii chekkaa...mwahhhh love you makrriiii "},
    {"date": "August 12", "letter": "L", "text": "Deyyy thirittu payaleww ninte loala hridhyam ipoll kallaaanu athu njan thalli pottikenenu mumbu nalla kochu ayikkoo innu kochinu njan rest tharuvaaa soo vannu enniku panavum prethapavum padi thannonem ilel ninew njan kollummmm... LOVE YOU "},
    {"date": "August 13", "letter": "M", "text": "CALL ME BITCH"},
    {"date": "August 14", "letter": "N", "text": "Hey my love ,How is your work going..HAPPY 3 YEAR 4 MONTH ANIVERSARY kunnjumanii😘😘😘its been this much time....🥹May we can hit above 50 years 🥹🥹ok whats today nothing special as usual blabbering😌😌i dont know whether you noticed that we were send paragrah on this day but now it is fading ,its months that i got a lovely paragrah from you...but it is fading and I dont want to be like that...this time I also wished you just in a line ,but things are changing you were the one who always wished me and memorized it but now i am the one😂😂ithe poloru 3 year 4 month oru vishu day night a kalla kuruneri ennodu ishtem ahnennu parenje,nthoru nanem ayirunnu chekkanu hooo ,njan povaaa,melody ntha ithra chocolate avan karenem ,nthokee ayirunnu mara makkri I LOVE YOU"},
    {"date": "August 15", "letter": "0", "text": "Halooo shundharrii,only 3 days left for your special day ,where you excited all this day to read this if YES just tell me what or how you feel.Today's topic it was a topic i am very much excited to share ,everything you read every day the things i already told you for thousand time.But I think this will make you go back to that old days i wish ....The magical ,most unprectable,the impossible happened day APRIL 13 2022 ,oh brooo i can see that each moment in my head very clearly ,eppo mothela enikku ninodu ishttem thiniyennu ennnu onum ariylilla ,i was comfortable with you ,i know that ninnaku enne ishttem ayirunnu ennu,bhavini edekku oro karym pareyumbol thanne enikku oreppayirunnu ninakku ene ishttem ahnennu,annu ni kanenem paremjile alel ente jevithathil oru chekkanem kaanannnu parenja appo block akkum but ni annu parenjapol ...I also wanted to see you njan eniitu kadel ninnu veetil poy oruggi mudi oke ketti kannu oke ezhuthi annu ayoo ninew kanda time was ninte aa chiri athu ippozhum entte manessil undu annu mothel kanan thodeggyatha ninte a nanem innum njan onnu aa kannil nookiya ninakku appo nanem avumm mangandii,enittu pittee day pinem kandu vishnu chetten ayy vannu enitoo oru pic edukkan vare chekkanu nanem hayoooooo,pine ulla oru karym nthannu vecha athu alel nale pareyam ok kunja BYE BYE I LOVE YOU "},
    {"date": "August 16", "letter": "P", "text": "Hey babe,How are you ,Today is a promise day ,I am going to promise somethings .I PROMISE I WILL NEVER USE HARSH WORDS TOWARDS YOU,I PROMISE I WILL NEVER HURT YOU WITH MY WORDS(you may get hurt but its not to be get hurted okay), I PROMISE TO KEEP THIS PROMISE, I PROMISE TO NEVER FIGHT WITH YOU NOT FOR CALLING ME OR TEXTING ME , I PROMISE TO NEVER LEAVE YOU, I PROMISE TO LOVE YOU UNCONDTIONALLY , I PROMISE TO RESPECT YOU, I PROMISE TO NEVER MAKE YOU CRY,I PROMISE TO NEVER HURT YOU HEART,I PROMISE TO LOVE YOU MORE CONSCIOUSLY,I PROMISE TO WORK ON MY EXPECTATIONS,I PROMISE TO NEVER LEAVE YOU SILENCE OR DISTANCE,I PROMISE,I PROMISE TO NEVER MAKE YOU WORRY , I PROMISE TO MAKE YOU HAPPY ,I PROMISE TO TRAVELL WITH YOU, I PROMISE TO STAY BY YOUR SIDE ,I PROMISE,I PROMISE THIS WASNT JUST A COUNTDOWN FOR YOUR BDAY IT WAS MY HEART ,You will be wondering why promises this sudden you will know why just wait for that day and you will get answer to all of your questions I LOVE YOU BYE BYE"},
    {"date": "August 17", "letter": "Q", "text": "Sunday aleeee... apoo free ayirikoolloooo apolll ntha cheyande ariyaloooo.... love you"}, 
    {"date": "August 18", "letter": "R", "text": "will see you tommorow babyy love you"},
    {"date": "August 19", "letter": "S", "text": "OOOHHH wow welcome to day 19 the special day🥳🥳🥳,HAPPY BIRTHDAY TO YOU KUNJUPPAPPPPPUUUU🥳😘🥹I MISS YOU ,I MISS SHARKY🫣,enttee thankamanii ponee I LOVE YOU SOO MUCH KUNJI MANIYE😘😘 ,agane kochinu 26 vayasayyy aaa agane prayem ayyy 🧓🧓makri kunju,May all the good things happen for you in this year 🥰,kochu financially stable avatte,entee kochinu ishttem ulla pole car okke modify cheyyan pattatte ,oru new Iphone edukkan pattatte,your dream bike edukkan pattatte ,ente kochinnu nashattapettathilum super helmet edukkan pattate ella agraheggalum nadekkate ente kochinte e varshem kond I KNOW YOU CAN AND YOU WILL we have 4 months left its easy right ni excpect polum cheyyatha work um appreciations kittatte ni swapnathil polum chinthikkaatha promotions kittatte,kochinte ella agrehem nadakkate ,stress oke koreyatte ,gym povan pattate ,everything ......May your life will filled with all the Happiness You deserve......🥰kayinja year I couldnt surprise you enikku oru vdo polum undakki tharan pateela and i know that you were very sad and disappointed,But this year I made it soo special,i dont know if i can afford a gift for you ,But with all I have this is a gift that I can afford🥰 ,MY TIME,MY LOVE .MY EFFORT AND ALL ,you will be pretty busy today right But I wish you were with me or I wish I could be there with you 🥰,but Thats okay vekkam varanem ketto ene kanan And may you MANIFEST all of your dreams I know and I am damn sure that you will be hellllaaahhhh successful in your life you already is but you have lot more to achieve and there are lot more you DESERVE in your work life ,you have a very kind and good heart which is belongs to meeeeeee..😌(dont you dare to give it to any one....😌)you will attract all the happiness love ,abundance in life,And you also have a message for tommorow the last and final one dont forget to open ,but the twist is it is not like other messages ,It will  have a password and the password is.......ofcourse I am not gonna tell you,You should figure it out All i will give is a hint (HINT: TWO THINGS I CRAVE OR WANT FROM YOU ____and____),let me see if you find it out 😌finally HAPPY BIRTHDAY TO THE MOST BEAUTIFUL PERSON IN MY LIFE😘 I LOVE YOU  AND you should only read it with an open heart ,when there is no one around you ,arum illathapol ni free ayy irikkumbol ni tension free stress free ayirikkumbol when you are at peace of mind ayirrikumbol dont read it when there is friends around you when you are distracted ,silent your phone give it whole heart and time ,it may take years or month or weak as you are busy with your life AND I dont care how much time will it take okayyy,ni ithrem okaa vaykumbol athil nthannu ariyan ulla akamsha undavum but dont... i want you to me mature and emotionally available when you are reading that okayyyy LOVE YOU KUNJUPPPAAA MWAHHHHH once again HAPPY BIRTHDAY 😘😘😘"},
]    



@app.route('/')
def index():
    return render_template('index.html')
from datetime import date, datetime, timedelta
import pytz

tz = pytz.timezone('Asia/Kolkata')

@app.route('/messages')
def message_list():
    today = datetime.now(tz).date()  # use India date
    start_date = date(2025, 8, 1)

    # ✅ Debugging: Check what date your code thinks it is
    print("TODAY:", today)

    unlocked_messages = []
    for msg in messages:
        msg_date = datetime.strptime(msg["date"] + " 2025", "%B %d %Y").date()
        print(msg["date"], msg_date, today >= msg_date)  # ✅ Debugging line
        if today >= msg_date:
            unlocked_messages.append(msg)

    return render_template('message.html', messages=unlocked_messages)


@app.route('/letter/<letter>')
def show_letter(letter):
    today = datetime.now(tz).date()
    start_date = date(2025, 8, 1)

    index = ord(letter.upper()) - 65  # A=0, B=1 ...
    unlock_date = start_date + timedelta(days=index)

    if today >= unlock_date:
        for msg in messages:
            if msg["letter"].upper() == letter.upper():
                return render_template('letter.html', letter=letter.upper(), message=msg["text"])
        return "Message not found", 404
    else:
        return "Not Available Yet", 403
    
@app.route('/day20', methods=['GET', 'POST'])
def day20():
    today = date.today()
    if today < date(2025, 8, 20):
        return "Nothing here kutta", 403

    if request.method == 'POST':
        password = request.form.get('password')
        if password == 'timeandlove':
            return render_template('day20.html')
        else:
            return render_template('day20.html', error="Wrong password!")
    return render_template('day20.html')

if __name__ == '__main__':
    app.run(debug=True)